language: java

before_script:
  - git clone --branch=master --depth=100 --quiet git://github.com/groupdocs/groupdocs-sdk-samples-uitests.git tests/samples-ui-tests
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cd tests/samples-ui-tests
  
script: mvn -q -s settings.xml clean test -Dsite.url="http://groupdocs-java-samples.herokuapp.com/"
