/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class AnnotationReplyInfo {
  private String guid = null;
  private String userGuid = null;
  private String userName = null;
  private String text = null;
  private Long repliedOn = null;
  private String parentReplyGuid = null;
  public String getGuid() {
    return guid;
  }
  public void setGuid(String guid) {
    this.guid = guid;
  }

  public String getUserGuid() {
    return userGuid;
  }
  public void setUserGuid(String userGuid) {
    this.userGuid = userGuid;
  }

  public String getUserName() {
    return userName;
  }
  public void setUserName(String userName) {
    this.userName = userName;
  }

  public String getText() {
    return text;
  }
  public void setText(String text) {
    this.text = text;
  }

  public Long getRepliedOn() {
    return repliedOn;
  }
  public void setRepliedOn(Long repliedOn) {
    this.repliedOn = repliedOn;
  }

  public String getParentReplyGuid() {
    return parentReplyGuid;
  }
  public void setParentReplyGuid(String parentReplyGuid) {
    this.parentReplyGuid = parentReplyGuid;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnnotationReplyInfo {\n");
    sb.append("  guid: ").append(guid).append("\n");
    sb.append("  userGuid: ").append(userGuid).append("\n");
    sb.append("  userName: ").append(userName).append("\n");
    sb.append("  text: ").append(text).append("\n");
    sb.append("  repliedOn: ").append(repliedOn).append("\n");
    sb.append("  parentReplyGuid: ").append(parentReplyGuid).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

