/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

import java.util.*;
import com.groupdocs.sdk.model.ChangeInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class ChangesResult {
  private String result_file_Id = null;
  private List<ChangeInfo> changes = new ArrayList<ChangeInfo>();
  public String getResult_file_Id() {
    return result_file_Id;
  }
  public void setResult_file_Id(String result_file_Id) {
    this.result_file_Id = result_file_Id;
  }

  public List<ChangeInfo> getChanges() {
    return changes;
  }
  public void setChanges(List<ChangeInfo> changes) {
    this.changes = changes;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChangesResult {\n");
    sb.append("  result_file_Id: ").append(result_file_Id).append("\n");
    sb.append("  changes: ").append(changes).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

