/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

import java.util.*;
import com.groupdocs.sdk.model.DatasourceField;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class Datasource {
  private Double id = null;
  private Double questionnaire_id = null;
  private String descr = null;
  private List<DatasourceField> fields = new ArrayList<DatasourceField>();
  private Long created_on = null;
  private Long modified_on = null;
  public Double getId() {
    return id;
  }
  public void setId(Double id) {
    this.id = id;
  }

  public Double getQuestionnaire_id() {
    return questionnaire_id;
  }
  public void setQuestionnaire_id(Double questionnaire_id) {
    this.questionnaire_id = questionnaire_id;
  }

  public String getDescr() {
    return descr;
  }
  public void setDescr(String descr) {
    this.descr = descr;
  }

  public List<DatasourceField> getFields() {
    return fields;
  }
  public void setFields(List<DatasourceField> fields) {
    this.fields = fields;
  }

  public Long getCreated_on() {
    return created_on;
  }
  public void setCreated_on(Long created_on) {
    this.created_on = created_on;
  }

  public Long getModified_on() {
    return modified_on;
  }
  public void setModified_on(Long modified_on) {
    this.modified_on = modified_on;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Datasource {\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  questionnaire_id: ").append(questionnaire_id).append("\n");
    sb.append("  descr: ").append(descr).append("\n");
    sb.append("  fields: ").append(fields).append("\n");
    sb.append("  created_on: ").append(created_on).append("\n");
    sb.append("  modified_on: ").append(modified_on).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

