/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

import java.util.*;
import com.groupdocs.sdk.model.AnnotationReplyInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class DeleteReplyResult {
  private String replyGuid = null;
  private String annotationGuid = null;
  private List<AnnotationReplyInfo> replies = new ArrayList<AnnotationReplyInfo>();
  public String getReplyGuid() {
    return replyGuid;
  }
  public void setReplyGuid(String replyGuid) {
    this.replyGuid = replyGuid;
  }

  public String getAnnotationGuid() {
    return annotationGuid;
  }
  public void setAnnotationGuid(String annotationGuid) {
    this.annotationGuid = annotationGuid;
  }

  public List<AnnotationReplyInfo> getReplies() {
    return replies;
  }
  public void setReplies(List<AnnotationReplyInfo> replies) {
    this.replies = replies;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteReplyResult {\n");
    sb.append("  replyGuid: ").append(replyGuid).append("\n");
    sb.append("  annotationGuid: ").append(annotationGuid).append("\n");
    sb.append("  replies: ").append(replies).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

