/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

import com.groupdocs.sdk.model.DocumentInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class DocumentViewInfo {
  private DocumentInfo document = null;
  private String short_url = null;
  private Long viewed_on = null;
  public DocumentInfo getDocument() {
    return document;
  }
  public void setDocument(DocumentInfo document) {
    this.document = document;
  }

  public String getShort_url() {
    return short_url;
  }
  public void setShort_url(String short_url) {
    this.short_url = short_url;
  }

  public Long getViewed_on() {
    return viewed_on;
  }
  public void setViewed_on(Long viewed_on) {
    this.viewed_on = viewed_on;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentViewInfo {\n");
    sb.append("  document: ").append(document).append("\n");
    sb.append("  short_url: ").append(short_url).append("\n");
    sb.append("  viewed_on: ").append(viewed_on).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

