/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

import com.groupdocs.sdk.model.DocumentInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class DocumentUserStatusResult {
  private DocumentInfo doc_info = null;
  private Double owner_id = null;
  private Double user_id = null;
  private String user_status = null;
  public DocumentInfo getDoc_info() {
    return doc_info;
  }
  public void setDoc_info(DocumentInfo doc_info) {
    this.doc_info = doc_info;
  }

  public Double getOwner_id() {
    return owner_id;
  }
  public void setOwner_id(Double owner_id) {
    this.owner_id = owner_id;
  }

  public Double getUser_id() {
    return user_id;
  }
  public void setUser_id(Double user_id) {
    this.user_id = user_id;
  }

  public String getUser_status() {
    return user_status;
  }
  public void setUser_status(String user_status) {
    this.user_status = user_status;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentUserStatusResult {\n");
    sb.append("  doc_info: ").append(doc_info).append("\n");
    sb.append("  owner_id: ").append(owner_id).append("\n");
    sb.append("  user_id: ").append(user_id).append("\n");
    sb.append("  user_status: ").append(user_status).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

