/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

import com.groupdocs.sdk.model.DocumentInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class FileMoveResult {
  private DocumentInfo src_file = null;
  private DocumentInfo dst_file = null;
  public DocumentInfo getSrc_file() {
    return src_file;
  }
  public void setSrc_file(DocumentInfo src_file) {
    this.src_file = src_file;
  }

  public DocumentInfo getDst_file() {
    return dst_file;
  }
  public void setDst_file(DocumentInfo dst_file) {
    this.dst_file = dst_file;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileMoveResult {\n");
    sb.append("  src_file: ").append(src_file).append("\n");
    sb.append("  dst_file: ").append(dst_file).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

