/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

import java.util.*;
import com.groupdocs.sdk.model.UserInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class FileSystemDocument {
  private String url = null;
  private Integer version = null;
  private String type = null;
  private String file_type = null;
  private Long size = null;
  private String thumbnail = null;
  private List<String> supported_types = new ArrayList<String>();
  private Double id = null;
  private String guid = null;
  private String name = null;
  private String access = null;
  private UserInfo owner = null;
  private List<UserInfo> sharers = new ArrayList<UserInfo>();
  private Boolean dir = null;
  private Long modified_on = null;
  private Long created_on = null;
  public String getUrl() {
    return url;
  }
  public void setUrl(String url) {
    this.url = url;
  }

  public Integer getVersion() {
    return version;
  }
  public void setVersion(Integer version) {
    this.version = version;
  }

  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }

  public String getFile_type() {
    return file_type;
  }
  public void setFile_type(String file_type) {
    this.file_type = file_type;
  }

  public Long getSize() {
    return size;
  }
  public void setSize(Long size) {
    this.size = size;
  }

  public String getThumbnail() {
    return thumbnail;
  }
  public void setThumbnail(String thumbnail) {
    this.thumbnail = thumbnail;
  }

  public List<String> getSupported_types() {
    return supported_types;
  }
  public void setSupported_types(List<String> supported_types) {
    this.supported_types = supported_types;
  }

  public Double getId() {
    return id;
  }
  public void setId(Double id) {
    this.id = id;
  }

  public String getGuid() {
    return guid;
  }
  public void setGuid(String guid) {
    this.guid = guid;
  }

  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  public String getAccess() {
    return access;
  }
  public void setAccess(String access) {
    this.access = access;
  }

  public UserInfo getOwner() {
    return owner;
  }
  public void setOwner(UserInfo owner) {
    this.owner = owner;
  }

  public List<UserInfo> getSharers() {
    return sharers;
  }
  public void setSharers(List<UserInfo> sharers) {
    this.sharers = sharers;
  }

  public Boolean getDir() {
    return dir;
  }
  public void setDir(Boolean dir) {
    this.dir = dir;
  }

  public Long getModified_on() {
    return modified_on;
  }
  public void setModified_on(Long modified_on) {
    this.modified_on = modified_on;
  }

  public Long getCreated_on() {
    return created_on;
  }
  public void setCreated_on(Long created_on) {
    this.created_on = created_on;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileSystemDocument {\n");
    sb.append("  url: ").append(url).append("\n");
    sb.append("  version: ").append(version).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("  file_type: ").append(file_type).append("\n");
    sb.append("  size: ").append(size).append("\n");
    sb.append("  thumbnail: ").append(thumbnail).append("\n");
    sb.append("  supported_types: ").append(supported_types).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  guid: ").append(guid).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  access: ").append(access).append("\n");
    sb.append("  owner: ").append(owner).append("\n");
    sb.append("  sharers: ").append(sharers).append("\n");
    sb.append("  dir: ").append(dir).append("\n");
    sb.append("  modified_on: ").append(modified_on).append("\n");
    sb.append("  created_on: ").append(created_on).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

