/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class FolderMoveResult {
  private String from_path = null;
  private String to_path = null;
  public String getFrom_path() {
    return from_path;
  }
  public void setFrom_path(String from_path) {
    this.from_path = from_path;
  }

  public String getTo_path() {
    return to_path;
  }
  public void setTo_path(String to_path) {
    this.to_path = to_path;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class FolderMoveResult {\n");
    sb.append("  from_path: ").append(from_path).append("\n");
    sb.append("  to_path: ").append(to_path).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

