/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class GetEditLockResult {
  private String doc_guid = null;
  private String file_id = null;
  private String edit_url = null;
  public String getDoc_guid() {
    return doc_guid;
  }
  public void setDoc_guid(String doc_guid) {
    this.doc_guid = doc_guid;
  }

  public String getFile_id() {
    return file_id;
  }
  public void setFile_id(String file_id) {
    this.file_id = file_id;
  }

  public String getEdit_url() {
    return edit_url;
  }
  public void setEdit_url(String edit_url) {
    this.edit_url = edit_url;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetEditLockResult {\n");
    sb.append("  doc_guid: ").append(doc_guid).append("\n");
    sb.append("  file_id: ").append(file_id).append("\n");
    sb.append("  edit_url: ").append(edit_url).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

