/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

import java.util.*;
import com.groupdocs.sdk.model.StorageProviderInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class GetStorageProvidersResult {
  private List<StorageProviderInfo> providers = new ArrayList<StorageProviderInfo>();
  public List<StorageProviderInfo> getProviders() {
    return providers;
  }
  public void setProviders(List<StorageProviderInfo> providers) {
    this.providers = providers;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetStorageProvidersResult {\n");
    sb.append("  providers: ").append(providers).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

