/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class JobErrorInfo {
  private Double job_id = null;
  private Double original_document_id = null;
  private Integer error_code = null;
  private String expected_format = null;
  public Double getJob_id() {
    return job_id;
  }
  public void setJob_id(Double job_id) {
    this.job_id = job_id;
  }

  public Double getOriginal_document_id() {
    return original_document_id;
  }
  public void setOriginal_document_id(Double original_document_id) {
    this.original_document_id = original_document_id;
  }

  public Integer getError_code() {
    return error_code;
  }
  public void setError_code(Integer error_code) {
    this.error_code = error_code;
  }

  public String getExpected_format() {
    return expected_format;
  }
  public void setExpected_format(String expected_format) {
    this.expected_format = expected_format;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobErrorInfo {\n");
    sb.append("  job_id: ").append(job_id).append("\n");
    sb.append("  original_document_id: ").append(original_document_id).append("\n");
    sb.append("  error_code: ").append(error_code).append("\n");
    sb.append("  expected_format: ").append(expected_format).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

