/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

import java.util.*;
import com.groupdocs.sdk.model.JobDocumentsEntry;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class JobInfo {
  private Double id = null;
  private List<String> out_formats = new ArrayList<String>();
  private String actions = null;
  private String status = null;
  private Boolean email_results = null;
  private Double priority = null;
  private Boolean url_only = null;
  private JobDocumentsEntry documents = null;
  private Long requested_time = null;
  private Long scheduled_time = null;
  private String guid = null;
  private String name = null;
  private String callback_url = null;
  public Double getId() {
    return id;
  }
  public void setId(Double id) {
    this.id = id;
  }

  public List<String> getOut_formats() {
    return out_formats;
  }
  public void setOut_formats(List<String> out_formats) {
    this.out_formats = out_formats;
  }

  public String getActions() {
    return actions;
  }
  public void setActions(String actions) {
    this.actions = actions;
  }

  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }

  public Boolean getEmail_results() {
    return email_results;
  }
  public void setEmail_results(Boolean email_results) {
    this.email_results = email_results;
  }

  public Double getPriority() {
    return priority;
  }
  public void setPriority(Double priority) {
    this.priority = priority;
  }

  public Boolean getUrl_only() {
    return url_only;
  }
  public void setUrl_only(Boolean url_only) {
    this.url_only = url_only;
  }

  public JobDocumentsEntry getDocuments() {
    return documents;
  }
  public void setDocuments(JobDocumentsEntry documents) {
    this.documents = documents;
  }

  public Long getRequested_time() {
    return requested_time;
  }
  public void setRequested_time(Long requested_time) {
    this.requested_time = requested_time;
  }

  public Long getScheduled_time() {
    return scheduled_time;
  }
  public void setScheduled_time(Long scheduled_time) {
    this.scheduled_time = scheduled_time;
  }

  public String getGuid() {
    return guid;
  }
  public void setGuid(String guid) {
    this.guid = guid;
  }

  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  public String getCallback_url() {
    return callback_url;
  }
  public void setCallback_url(String callback_url) {
    this.callback_url = callback_url;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobInfo {\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  out_formats: ").append(out_formats).append("\n");
    sb.append("  actions: ").append(actions).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  email_results: ").append(email_results).append("\n");
    sb.append("  priority: ").append(priority).append("\n");
    sb.append("  url_only: ").append(url_only).append("\n");
    sb.append("  documents: ").append(documents).append("\n");
    sb.append("  requested_time: ").append(requested_time).append("\n");
    sb.append("  scheduled_time: ").append(scheduled_time).append("\n");
    sb.append("  guid: ").append(guid).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  callback_url: ").append(callback_url).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

