/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class Page {
  private Integer id = null;
  private Double w = null;
  private Double h = null;
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  public Double getW() {
    return w;
  }
  public void setW(Double w) {
    this.w = w;
  }

  public Double getH() {
    return h;
  }
  public void setH(Double h) {
    this.h = h;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Page {\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  w: ").append(w).append("\n");
    sb.append("  h: ").append(h).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

