/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class ReviewerInfo {
  private Double id = null;
  private String guid = null;
  private String primary_email = null;
  private String firstName = null;
  private String lastName = null;
  private Integer access_rights = null;
  private Integer color = null;
  private String customEmailMessage = null;
  public Double getId() {
    return id;
  }
  public void setId(Double id) {
    this.id = id;
  }

  public String getGuid() {
    return guid;
  }
  public void setGuid(String guid) {
    this.guid = guid;
  }

  public String getPrimary_email() {
    return primary_email;
  }
  public void setPrimary_email(String primary_email) {
    this.primary_email = primary_email;
  }

  public String getFirstName() {
    return firstName;
  }
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public String getLastName() {
    return lastName;
  }
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public Integer getAccess_rights() {
    return access_rights;
  }
  public void setAccess_rights(Integer access_rights) {
    this.access_rights = access_rights;
  }

  public Integer getColor() {
    return color;
  }
  public void setColor(Integer color) {
    this.color = color;
  }

  public String getCustomEmailMessage() {
    return customEmailMessage;
  }
  public void setCustomEmailMessage(String customEmailMessage) {
    this.customEmailMessage = customEmailMessage;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReviewerInfo {\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  guid: ").append(guid).append("\n");
    sb.append("  primary_email: ").append(primary_email).append("\n");
    sb.append("  firstName: ").append(firstName).append("\n");
    sb.append("  lastName: ").append(lastName).append("\n");
    sb.append("  access_rights: ").append(access_rights).append("\n");
    sb.append("  color: ").append(color).append("\n");
    sb.append("  customEmailMessage: ").append(customEmailMessage).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

