/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

import java.util.*;
import com.groupdocs.sdk.model.ReviewerInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class SetCollaboratorsResult {
  private String documentGuid = null;
  private String sessionGuid = null;
  private ReviewerInfo owner = null;
  private List<ReviewerInfo> collaborators = new ArrayList<ReviewerInfo>();
  public String getDocumentGuid() {
    return documentGuid;
  }
  public void setDocumentGuid(String documentGuid) {
    this.documentGuid = documentGuid;
  }

  public String getSessionGuid() {
    return sessionGuid;
  }
  public void setSessionGuid(String sessionGuid) {
    this.sessionGuid = sessionGuid;
  }

  public ReviewerInfo getOwner() {
    return owner;
  }
  public void setOwner(ReviewerInfo owner) {
    this.owner = owner;
  }

  public List<ReviewerInfo> getCollaborators() {
    return collaborators;
  }
  public void setCollaborators(List<ReviewerInfo> collaborators) {
    this.collaborators = collaborators;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SetCollaboratorsResult {\n");
    sb.append("  documentGuid: ").append(documentGuid).append("\n");
    sb.append("  sessionGuid: ").append(sessionGuid).append("\n");
    sb.append("  owner: ").append(owner).append("\n");
    sb.append("  collaborators: ").append(collaborators).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

