/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

import java.util.*;
import com.groupdocs.sdk.model.SignatureEnvelopeRecipientInfo;
import com.groupdocs.sdk.model.SignatureEnvelopeDocumentInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class SignatureEnvelopeResourcesResult {
  private List<SignatureEnvelopeDocumentInfo> documents = new ArrayList<SignatureEnvelopeDocumentInfo>();
  private List<SignatureEnvelopeRecipientInfo> recipients = new ArrayList<SignatureEnvelopeRecipientInfo>();
  private List<String> dates = new ArrayList<String>();
  public List<SignatureEnvelopeDocumentInfo> getDocuments() {
    return documents;
  }
  public void setDocuments(List<SignatureEnvelopeDocumentInfo> documents) {
    this.documents = documents;
  }

  public List<SignatureEnvelopeRecipientInfo> getRecipients() {
    return recipients;
  }
  public void setRecipients(List<SignatureEnvelopeRecipientInfo> recipients) {
    this.recipients = recipients;
  }

  public List<String> getDates() {
    return dates;
  }
  public void setDates(List<String> dates) {
    this.dates = dates;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureEnvelopeResourcesResult {\n");
    sb.append("  documents: ").append(documents).append("\n");
    sb.append("  recipients: ").append(recipients).append("\n");
    sb.append("  dates: ").append(dates).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

