/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

import java.util.*;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class SignatureFormInfo {
  private String id = null;
  private String name = null;
  private String ownerGuid = null;
  private String templateGuid = null;
  private String createdTimeStamp = null;
  private Integer status = null;
  private String statusDateTime = null;
  private Double documentsCount = null;
  private Double documentsPages = null;
  private Double participantsCount = null;
  private List<String> fieldsInFinalFileName = new ArrayList<String>();
  private Boolean canParticipantDownloadForm = null;
  private String waterMarkText = null;
  private String waterMarkImage = null;
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  public String getOwnerGuid() {
    return ownerGuid;
  }
  public void setOwnerGuid(String ownerGuid) {
    this.ownerGuid = ownerGuid;
  }

  public String getTemplateGuid() {
    return templateGuid;
  }
  public void setTemplateGuid(String templateGuid) {
    this.templateGuid = templateGuid;
  }

  public String getCreatedTimeStamp() {
    return createdTimeStamp;
  }
  public void setCreatedTimeStamp(String createdTimeStamp) {
    this.createdTimeStamp = createdTimeStamp;
  }

  public Integer getStatus() {
    return status;
  }
  public void setStatus(Integer status) {
    this.status = status;
  }

  public String getStatusDateTime() {
    return statusDateTime;
  }
  public void setStatusDateTime(String statusDateTime) {
    this.statusDateTime = statusDateTime;
  }

  public Double getDocumentsCount() {
    return documentsCount;
  }
  public void setDocumentsCount(Double documentsCount) {
    this.documentsCount = documentsCount;
  }

  public Double getDocumentsPages() {
    return documentsPages;
  }
  public void setDocumentsPages(Double documentsPages) {
    this.documentsPages = documentsPages;
  }

  public Double getParticipantsCount() {
    return participantsCount;
  }
  public void setParticipantsCount(Double participantsCount) {
    this.participantsCount = participantsCount;
  }

  public List<String> getFieldsInFinalFileName() {
    return fieldsInFinalFileName;
  }
  public void setFieldsInFinalFileName(List<String> fieldsInFinalFileName) {
    this.fieldsInFinalFileName = fieldsInFinalFileName;
  }

  public Boolean getCanParticipantDownloadForm() {
    return canParticipantDownloadForm;
  }
  public void setCanParticipantDownloadForm(Boolean canParticipantDownloadForm) {
    this.canParticipantDownloadForm = canParticipantDownloadForm;
  }

  public String getWaterMarkText() {
    return waterMarkText;
  }
  public void setWaterMarkText(String waterMarkText) {
    this.waterMarkText = waterMarkText;
  }

  public String getWaterMarkImage() {
    return waterMarkImage;
  }
  public void setWaterMarkImage(String waterMarkImage) {
    this.waterMarkImage = waterMarkImage;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureFormInfo {\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  ownerGuid: ").append(ownerGuid).append("\n");
    sb.append("  templateGuid: ").append(templateGuid).append("\n");
    sb.append("  createdTimeStamp: ").append(createdTimeStamp).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  statusDateTime: ").append(statusDateTime).append("\n");
    sb.append("  documentsCount: ").append(documentsCount).append("\n");
    sb.append("  documentsPages: ").append(documentsPages).append("\n");
    sb.append("  participantsCount: ").append(participantsCount).append("\n");
    sb.append("  fieldsInFinalFileName: ").append(fieldsInFinalFileName).append("\n");
    sb.append("  canParticipantDownloadForm: ").append(canParticipantDownloadForm).append("\n");
    sb.append("  waterMarkText: ").append(waterMarkText).append("\n");
    sb.append("  waterMarkImage: ").append(waterMarkImage).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

