/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class SignatureEnvelopeRecipientInfo {
  private String id = null;
  private String firstName = null;
  private String lastName = null;
  private String email = null;
  private String userGuid = null;
  private Integer order = null;
  private Double roleId = null;
  private Integer status = null;
  private String statusMessage = null;
  private String statusDateTime = null;
  private Double delegatedRecipientId = null;
  private String signatureFingerprint = null;
  private String signatureHost = null;
  private String signatureLocation = null;
  private String signatureBrowser = null;
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  public String getFirstName() {
    return firstName;
  }
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public String getLastName() {
    return lastName;
  }
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  public String getUserGuid() {
    return userGuid;
  }
  public void setUserGuid(String userGuid) {
    this.userGuid = userGuid;
  }

  public Integer getOrder() {
    return order;
  }
  public void setOrder(Integer order) {
    this.order = order;
  }

  public Double getRoleId() {
    return roleId;
  }
  public void setRoleId(Double roleId) {
    this.roleId = roleId;
  }

  public Integer getStatus() {
    return status;
  }
  public void setStatus(Integer status) {
    this.status = status;
  }

  public String getStatusMessage() {
    return statusMessage;
  }
  public void setStatusMessage(String statusMessage) {
    this.statusMessage = statusMessage;
  }

  public String getStatusDateTime() {
    return statusDateTime;
  }
  public void setStatusDateTime(String statusDateTime) {
    this.statusDateTime = statusDateTime;
  }

  public Double getDelegatedRecipientId() {
    return delegatedRecipientId;
  }
  public void setDelegatedRecipientId(Double delegatedRecipientId) {
    this.delegatedRecipientId = delegatedRecipientId;
  }

  public String getSignatureFingerprint() {
    return signatureFingerprint;
  }
  public void setSignatureFingerprint(String signatureFingerprint) {
    this.signatureFingerprint = signatureFingerprint;
  }

  public String getSignatureHost() {
    return signatureHost;
  }
  public void setSignatureHost(String signatureHost) {
    this.signatureHost = signatureHost;
  }

  public String getSignatureLocation() {
    return signatureLocation;
  }
  public void setSignatureLocation(String signatureLocation) {
    this.signatureLocation = signatureLocation;
  }

  public String getSignatureBrowser() {
    return signatureBrowser;
  }
  public void setSignatureBrowser(String signatureBrowser) {
    this.signatureBrowser = signatureBrowser;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureEnvelopeRecipientInfo {\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  firstName: ").append(firstName).append("\n");
    sb.append("  lastName: ").append(lastName).append("\n");
    sb.append("  email: ").append(email).append("\n");
    sb.append("  userGuid: ").append(userGuid).append("\n");
    sb.append("  order: ").append(order).append("\n");
    sb.append("  roleId: ").append(roleId).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  statusMessage: ").append(statusMessage).append("\n");
    sb.append("  statusDateTime: ").append(statusDateTime).append("\n");
    sb.append("  delegatedRecipientId: ").append(delegatedRecipientId).append("\n");
    sb.append("  signatureFingerprint: ").append(signatureFingerprint).append("\n");
    sb.append("  signatureHost: ").append(signatureHost).append("\n");
    sb.append("  signatureLocation: ").append(signatureLocation).append("\n");
    sb.append("  signatureBrowser: ").append(signatureBrowser).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

