/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class SignatureTemplateDocumentInfo {
  private String documentId = null;
  private String templateId = null;
  private Integer order = null;
  private String name = null;
  private String originalDocumentMD5 = null;
  private Integer originalDocumentPagesCount = null;
  private Integer fieldsCount = null;
  public String getDocumentId() {
    return documentId;
  }
  public void setDocumentId(String documentId) {
    this.documentId = documentId;
  }

  public String getTemplateId() {
    return templateId;
  }
  public void setTemplateId(String templateId) {
    this.templateId = templateId;
  }

  public Integer getOrder() {
    return order;
  }
  public void setOrder(Integer order) {
    this.order = order;
  }

  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  public String getOriginalDocumentMD5() {
    return originalDocumentMD5;
  }
  public void setOriginalDocumentMD5(String originalDocumentMD5) {
    this.originalDocumentMD5 = originalDocumentMD5;
  }

  public Integer getOriginalDocumentPagesCount() {
    return originalDocumentPagesCount;
  }
  public void setOriginalDocumentPagesCount(Integer originalDocumentPagesCount) {
    this.originalDocumentPagesCount = originalDocumentPagesCount;
  }

  public Integer getFieldsCount() {
    return fieldsCount;
  }
  public void setFieldsCount(Integer fieldsCount) {
    this.fieldsCount = fieldsCount;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureTemplateDocumentInfo {\n");
    sb.append("  documentId: ").append(documentId).append("\n");
    sb.append("  templateId: ").append(templateId).append("\n");
    sb.append("  order: ").append(order).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  originalDocumentMD5: ").append(originalDocumentMD5).append("\n");
    sb.append("  originalDocumentPagesCount: ").append(originalDocumentPagesCount).append("\n");
    sb.append("  fieldsCount: ").append(fieldsCount).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

