/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

import java.util.*;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class StorageProviderInfo {
  private Double id = null;
  private String provider = null;
  private String type = null;
  private List<Integer> token = new ArrayList<Integer>();
  private String publicKey = null;
  private String privateKey = null;
  private String rootFolder = null;
  private Boolean isPrimary = null;
  private String serviceHost = null;
  public Double getId() {
    return id;
  }
  public void setId(Double id) {
    this.id = id;
  }

  public String getProvider() {
    return provider;
  }
  public void setProvider(String provider) {
    this.provider = provider;
  }

  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }

  public List<Integer> getToken() {
    return token;
  }
  public void setToken(List<Integer> token) {
    this.token = token;
  }

  public String getPublicKey() {
    return publicKey;
  }
  public void setPublicKey(String publicKey) {
    this.publicKey = publicKey;
  }

  public String getPrivateKey() {
    return privateKey;
  }
  public void setPrivateKey(String privateKey) {
    this.privateKey = privateKey;
  }

  public String getRootFolder() {
    return rootFolder;
  }
  public void setRootFolder(String rootFolder) {
    this.rootFolder = rootFolder;
  }

  public Boolean getIsPrimary() {
    return isPrimary;
  }
  public void setIsPrimary(Boolean isPrimary) {
    this.isPrimary = isPrimary;
  }

  public String getServiceHost() {
    return serviceHost;
  }
  public void setServiceHost(String serviceHost) {
    this.serviceHost = serviceHost;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class StorageProviderInfo {\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  provider: ").append(provider).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("  token: ").append(token).append("\n");
    sb.append("  publicKey: ").append(publicKey).append("\n");
    sb.append("  privateKey: ").append(privateKey).append("\n");
    sb.append("  rootFolder: ").append(rootFolder).append("\n");
    sb.append("  isPrimary: ").append(isPrimary).append("\n");
    sb.append("  serviceHost: ").append(serviceHost).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

