/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class TextFieldInfo {
  private String fieldText = null;
  private String fontFamily = null;
  private Double fontSize = null;
  public String getFieldText() {
    return fieldText;
  }
  public void setFieldText(String fieldText) {
    this.fieldText = fieldText;
  }

  public String getFontFamily() {
    return fontFamily;
  }
  public void setFontFamily(String fontFamily) {
    this.fontFamily = fontFamily;
  }

  public Double getFontSize() {
    return fontSize;
  }
  public void setFontSize(Double fontSize) {
    this.fontSize = fontSize;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class TextFieldInfo {\n");
    sb.append("  fieldText: ").append(fieldText).append("\n");
    sb.append("  fontFamily: ").append(fontFamily).append("\n");
    sb.append("  fontSize: ").append(fontSize).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

