/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

import com.groupdocs.sdk.model.UserIdentity;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class UserEmbedKeyInfo {
  private UserIdentity user = null;
  private String guid = null;
  private String area = null;
  private Boolean active = null;
  private Integer hit_count = null;
  public UserIdentity getUser() {
    return user;
  }
  public void setUser(UserIdentity user) {
    this.user = user;
  }

  public String getGuid() {
    return guid;
  }
  public void setGuid(String guid) {
    this.guid = guid;
  }

  public String getArea() {
    return area;
  }
  public void setArea(String area) {
    this.area = area;
  }

  public Boolean getActive() {
    return active;
  }
  public void setActive(Boolean active) {
    this.active = active;
  }

  public Integer getHit_count() {
    return hit_count;
  }
  public void setHit_count(Integer hit_count) {
    this.hit_count = hit_count;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserEmbedKeyInfo {\n");
    sb.append("  user: ").append(user).append("\n");
    sb.append("  guid: ").append(guid).append("\n");
    sb.append("  area: ").append(area).append("\n");
    sb.append("  active: ").append(active).append("\n");
    sb.append("  hit_count: ").append(hit_count).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

