/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class UserPasswordInfo {
  private String old_pswd_salt = null;
  private String new_pswd_salt = null;
  private String reset_token = null;
  public String getOld_pswd_salt() {
    return old_pswd_salt;
  }
  public void setOld_pswd_salt(String old_pswd_salt) {
    this.old_pswd_salt = old_pswd_salt;
  }

  public String getNew_pswd_salt() {
    return new_pswd_salt;
  }
  public void setNew_pswd_salt(String new_pswd_salt) {
    this.new_pswd_salt = new_pswd_salt;
  }

  public String getReset_token() {
    return reset_token;
  }
  public void setReset_token(String reset_token) {
    this.reset_token = reset_token;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserPasswordInfo {\n");
    sb.append("  old_pswd_salt: ").append(old_pswd_salt).append("\n");
    sb.append("  new_pswd_salt: ").append(new_pswd_salt).append("\n");
    sb.append("  reset_token: ").append(reset_token).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

