/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.groupdocs.sdk.model;

import java.util.*;
import com.groupdocs.sdk.model.RoleInfo;
/**
 * 
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
public class UserInfo {
  private String nickname = null;
  private String firstname = null;
  private String lastname = null;
  private String pkey = null;
  private String pswd_salt = null;
  private String claimed_id = null;
  private String token = null;
  private Integer storage = null;
  private List<Integer> photo = new ArrayList<Integer>();
  private Boolean active = null;
  private Boolean trial = null;
  private Boolean news_eanbled = null;
  private Boolean alerts_eanbled = null;
  private Boolean support_eanbled = null;
  private String support_email = null;
  private Boolean annotation_branded = null;
  private Boolean viewer_branded = null;
  private Boolean is_real_time_broadcast_enabled = null;
  private Boolean is_scroll_broadcast_enabled = null;
  private Boolean is_zoom_broadcast_enabled = null;
  private List<Integer> annotation_logo = new ArrayList<Integer>();
  private List<Integer> pointer_tool_cursor = new ArrayList<Integer>();
  private Integer annotation_header_options = null;
  private Boolean is_annotation_navigation_widget_enabled = null;
  private Boolean is_annotation_zoom_widget_enabled = null;
  private Boolean is_annotation_download_widget_enabled = null;
  private Boolean is_annotation_print_widget_enabled = null;
  private Boolean is_annotation_help_widget_enabled = null;
  private Boolean is_right_panel_enabled = null;
  private Boolean is_thumbnails_panel_enabled = null;
  private Boolean is_standard_header_always_shown = null;
  private Boolean is_toolbar_enabled = null;
  private Boolean is_text_annotation_button_enabled = null;
  private Boolean is_rectangle_annotation_button_enabled = null;
  private Boolean is_point_annotation_button_enabled = null;
  private Boolean is_strikeout_annotation_button_enabled = null;
  private Boolean is_polyline_annotation_button_enabled = null;
  private Boolean is_typewriter_annotation_button_enabled = null;
  private Boolean is_watermark_annotation_button_enabled = null;
  private List<Integer> viewer_logo = new ArrayList<Integer>();
  private Integer viewer_options = null;
  private Boolean is_viewer_navigation_widget_enabled = null;
  private Boolean is_viewer_zoom_widget_enabled = null;
  private Boolean is_viewer_download_widget_enabled = null;
  private Boolean is_viewer_print_widget_enabled = null;
  private Boolean is_viewer_help_widget_enabled = null;
  private Long signedupOn = null;
  private Long signedinOn = null;
  private Integer signin_count = null;
  private List<RoleInfo> roles = new ArrayList<RoleInfo>();
  private Double id = null;
  private String guid = null;
  private String primary_email = null;
  public String getNickname() {
    return nickname;
  }
  public void setNickname(String nickname) {
    this.nickname = nickname;
  }

  public String getFirstname() {
    return firstname;
  }
  public void setFirstname(String firstname) {
    this.firstname = firstname;
  }

  public String getLastname() {
    return lastname;
  }
  public void setLastname(String lastname) {
    this.lastname = lastname;
  }

  public String getPkey() {
    return pkey;
  }
  public void setPkey(String pkey) {
    this.pkey = pkey;
  }

  public String getPswd_salt() {
    return pswd_salt;
  }
  public void setPswd_salt(String pswd_salt) {
    this.pswd_salt = pswd_salt;
  }

  public String getClaimed_id() {
    return claimed_id;
  }
  public void setClaimed_id(String claimed_id) {
    this.claimed_id = claimed_id;
  }

  public String getToken() {
    return token;
  }
  public void setToken(String token) {
    this.token = token;
  }

  public Integer getStorage() {
    return storage;
  }
  public void setStorage(Integer storage) {
    this.storage = storage;
  }

  public List<Integer> getPhoto() {
    return photo;
  }
  public void setPhoto(List<Integer> photo) {
    this.photo = photo;
  }

  public Boolean getActive() {
    return active;
  }
  public void setActive(Boolean active) {
    this.active = active;
  }

  public Boolean getTrial() {
    return trial;
  }
  public void setTrial(Boolean trial) {
    this.trial = trial;
  }

  public Boolean getNews_eanbled() {
    return news_eanbled;
  }
  public void setNews_eanbled(Boolean news_eanbled) {
    this.news_eanbled = news_eanbled;
  }

  public Boolean getAlerts_eanbled() {
    return alerts_eanbled;
  }
  public void setAlerts_eanbled(Boolean alerts_eanbled) {
    this.alerts_eanbled = alerts_eanbled;
  }

  public Boolean getSupport_eanbled() {
    return support_eanbled;
  }
  public void setSupport_eanbled(Boolean support_eanbled) {
    this.support_eanbled = support_eanbled;
  }

  public String getSupport_email() {
    return support_email;
  }
  public void setSupport_email(String support_email) {
    this.support_email = support_email;
  }

  public Boolean getAnnotation_branded() {
    return annotation_branded;
  }
  public void setAnnotation_branded(Boolean annotation_branded) {
    this.annotation_branded = annotation_branded;
  }

  public Boolean getViewer_branded() {
    return viewer_branded;
  }
  public void setViewer_branded(Boolean viewer_branded) {
    this.viewer_branded = viewer_branded;
  }

  public Boolean getIs_real_time_broadcast_enabled() {
    return is_real_time_broadcast_enabled;
  }
  public void setIs_real_time_broadcast_enabled(Boolean is_real_time_broadcast_enabled) {
    this.is_real_time_broadcast_enabled = is_real_time_broadcast_enabled;
  }

  public Boolean getIs_scroll_broadcast_enabled() {
    return is_scroll_broadcast_enabled;
  }
  public void setIs_scroll_broadcast_enabled(Boolean is_scroll_broadcast_enabled) {
    this.is_scroll_broadcast_enabled = is_scroll_broadcast_enabled;
  }

  public Boolean getIs_zoom_broadcast_enabled() {
    return is_zoom_broadcast_enabled;
  }
  public void setIs_zoom_broadcast_enabled(Boolean is_zoom_broadcast_enabled) {
    this.is_zoom_broadcast_enabled = is_zoom_broadcast_enabled;
  }

  public List<Integer> getAnnotation_logo() {
    return annotation_logo;
  }
  public void setAnnotation_logo(List<Integer> annotation_logo) {
    this.annotation_logo = annotation_logo;
  }

  public List<Integer> getPointer_tool_cursor() {
    return pointer_tool_cursor;
  }
  public void setPointer_tool_cursor(List<Integer> pointer_tool_cursor) {
    this.pointer_tool_cursor = pointer_tool_cursor;
  }

  public Integer getAnnotation_header_options() {
    return annotation_header_options;
  }
  public void setAnnotation_header_options(Integer annotation_header_options) {
    this.annotation_header_options = annotation_header_options;
  }

  public Boolean getIs_annotation_navigation_widget_enabled() {
    return is_annotation_navigation_widget_enabled;
  }
  public void setIs_annotation_navigation_widget_enabled(Boolean is_annotation_navigation_widget_enabled) {
    this.is_annotation_navigation_widget_enabled = is_annotation_navigation_widget_enabled;
  }

  public Boolean getIs_annotation_zoom_widget_enabled() {
    return is_annotation_zoom_widget_enabled;
  }
  public void setIs_annotation_zoom_widget_enabled(Boolean is_annotation_zoom_widget_enabled) {
    this.is_annotation_zoom_widget_enabled = is_annotation_zoom_widget_enabled;
  }

  public Boolean getIs_annotation_download_widget_enabled() {
    return is_annotation_download_widget_enabled;
  }
  public void setIs_annotation_download_widget_enabled(Boolean is_annotation_download_widget_enabled) {
    this.is_annotation_download_widget_enabled = is_annotation_download_widget_enabled;
  }

  public Boolean getIs_annotation_print_widget_enabled() {
    return is_annotation_print_widget_enabled;
  }
  public void setIs_annotation_print_widget_enabled(Boolean is_annotation_print_widget_enabled) {
    this.is_annotation_print_widget_enabled = is_annotation_print_widget_enabled;
  }

  public Boolean getIs_annotation_help_widget_enabled() {
    return is_annotation_help_widget_enabled;
  }
  public void setIs_annotation_help_widget_enabled(Boolean is_annotation_help_widget_enabled) {
    this.is_annotation_help_widget_enabled = is_annotation_help_widget_enabled;
  }

  public Boolean getIs_right_panel_enabled() {
    return is_right_panel_enabled;
  }
  public void setIs_right_panel_enabled(Boolean is_right_panel_enabled) {
    this.is_right_panel_enabled = is_right_panel_enabled;
  }

  public Boolean getIs_thumbnails_panel_enabled() {
    return is_thumbnails_panel_enabled;
  }
  public void setIs_thumbnails_panel_enabled(Boolean is_thumbnails_panel_enabled) {
    this.is_thumbnails_panel_enabled = is_thumbnails_panel_enabled;
  }

  public Boolean getIs_standard_header_always_shown() {
    return is_standard_header_always_shown;
  }
  public void setIs_standard_header_always_shown(Boolean is_standard_header_always_shown) {
    this.is_standard_header_always_shown = is_standard_header_always_shown;
  }

  public Boolean getIs_toolbar_enabled() {
    return is_toolbar_enabled;
  }
  public void setIs_toolbar_enabled(Boolean is_toolbar_enabled) {
    this.is_toolbar_enabled = is_toolbar_enabled;
  }

  public Boolean getIs_text_annotation_button_enabled() {
    return is_text_annotation_button_enabled;
  }
  public void setIs_text_annotation_button_enabled(Boolean is_text_annotation_button_enabled) {
    this.is_text_annotation_button_enabled = is_text_annotation_button_enabled;
  }

  public Boolean getIs_rectangle_annotation_button_enabled() {
    return is_rectangle_annotation_button_enabled;
  }
  public void setIs_rectangle_annotation_button_enabled(Boolean is_rectangle_annotation_button_enabled) {
    this.is_rectangle_annotation_button_enabled = is_rectangle_annotation_button_enabled;
  }

  public Boolean getIs_point_annotation_button_enabled() {
    return is_point_annotation_button_enabled;
  }
  public void setIs_point_annotation_button_enabled(Boolean is_point_annotation_button_enabled) {
    this.is_point_annotation_button_enabled = is_point_annotation_button_enabled;
  }

  public Boolean getIs_strikeout_annotation_button_enabled() {
    return is_strikeout_annotation_button_enabled;
  }
  public void setIs_strikeout_annotation_button_enabled(Boolean is_strikeout_annotation_button_enabled) {
    this.is_strikeout_annotation_button_enabled = is_strikeout_annotation_button_enabled;
  }

  public Boolean getIs_polyline_annotation_button_enabled() {
    return is_polyline_annotation_button_enabled;
  }
  public void setIs_polyline_annotation_button_enabled(Boolean is_polyline_annotation_button_enabled) {
    this.is_polyline_annotation_button_enabled = is_polyline_annotation_button_enabled;
  }

  public Boolean getIs_typewriter_annotation_button_enabled() {
    return is_typewriter_annotation_button_enabled;
  }
  public void setIs_typewriter_annotation_button_enabled(Boolean is_typewriter_annotation_button_enabled) {
    this.is_typewriter_annotation_button_enabled = is_typewriter_annotation_button_enabled;
  }

  public Boolean getIs_watermark_annotation_button_enabled() {
    return is_watermark_annotation_button_enabled;
  }
  public void setIs_watermark_annotation_button_enabled(Boolean is_watermark_annotation_button_enabled) {
    this.is_watermark_annotation_button_enabled = is_watermark_annotation_button_enabled;
  }

  public List<Integer> getViewer_logo() {
    return viewer_logo;
  }
  public void setViewer_logo(List<Integer> viewer_logo) {
    this.viewer_logo = viewer_logo;
  }

  public Integer getViewer_options() {
    return viewer_options;
  }
  public void setViewer_options(Integer viewer_options) {
    this.viewer_options = viewer_options;
  }

  public Boolean getIs_viewer_navigation_widget_enabled() {
    return is_viewer_navigation_widget_enabled;
  }
  public void setIs_viewer_navigation_widget_enabled(Boolean is_viewer_navigation_widget_enabled) {
    this.is_viewer_navigation_widget_enabled = is_viewer_navigation_widget_enabled;
  }

  public Boolean getIs_viewer_zoom_widget_enabled() {
    return is_viewer_zoom_widget_enabled;
  }
  public void setIs_viewer_zoom_widget_enabled(Boolean is_viewer_zoom_widget_enabled) {
    this.is_viewer_zoom_widget_enabled = is_viewer_zoom_widget_enabled;
  }

  public Boolean getIs_viewer_download_widget_enabled() {
    return is_viewer_download_widget_enabled;
  }
  public void setIs_viewer_download_widget_enabled(Boolean is_viewer_download_widget_enabled) {
    this.is_viewer_download_widget_enabled = is_viewer_download_widget_enabled;
  }

  public Boolean getIs_viewer_print_widget_enabled() {
    return is_viewer_print_widget_enabled;
  }
  public void setIs_viewer_print_widget_enabled(Boolean is_viewer_print_widget_enabled) {
    this.is_viewer_print_widget_enabled = is_viewer_print_widget_enabled;
  }

  public Boolean getIs_viewer_help_widget_enabled() {
    return is_viewer_help_widget_enabled;
  }
  public void setIs_viewer_help_widget_enabled(Boolean is_viewer_help_widget_enabled) {
    this.is_viewer_help_widget_enabled = is_viewer_help_widget_enabled;
  }

  public Long getSignedupOn() {
    return signedupOn;
  }
  public void setSignedupOn(Long signedupOn) {
    this.signedupOn = signedupOn;
  }

  public Long getSignedinOn() {
    return signedinOn;
  }
  public void setSignedinOn(Long signedinOn) {
    this.signedinOn = signedinOn;
  }

  public Integer getSignin_count() {
    return signin_count;
  }
  public void setSignin_count(Integer signin_count) {
    this.signin_count = signin_count;
  }

  public List<RoleInfo> getRoles() {
    return roles;
  }
  public void setRoles(List<RoleInfo> roles) {
    this.roles = roles;
  }

  public Double getId() {
    return id;
  }
  public void setId(Double id) {
    this.id = id;
  }

  public String getGuid() {
    return guid;
  }
  public void setGuid(String guid) {
    this.guid = guid;
  }

  public String getPrimary_email() {
    return primary_email;
  }
  public void setPrimary_email(String primary_email) {
    this.primary_email = primary_email;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserInfo {\n");
    sb.append("  nickname: ").append(nickname).append("\n");
    sb.append("  firstname: ").append(firstname).append("\n");
    sb.append("  lastname: ").append(lastname).append("\n");
    sb.append("  pkey: ").append(pkey).append("\n");
    sb.append("  pswd_salt: ").append(pswd_salt).append("\n");
    sb.append("  claimed_id: ").append(claimed_id).append("\n");
    sb.append("  token: ").append(token).append("\n");
    sb.append("  storage: ").append(storage).append("\n");
    sb.append("  photo: ").append(photo).append("\n");
    sb.append("  active: ").append(active).append("\n");
    sb.append("  trial: ").append(trial).append("\n");
    sb.append("  news_eanbled: ").append(news_eanbled).append("\n");
    sb.append("  alerts_eanbled: ").append(alerts_eanbled).append("\n");
    sb.append("  support_eanbled: ").append(support_eanbled).append("\n");
    sb.append("  support_email: ").append(support_email).append("\n");
    sb.append("  annotation_branded: ").append(annotation_branded).append("\n");
    sb.append("  viewer_branded: ").append(viewer_branded).append("\n");
    sb.append("  is_real_time_broadcast_enabled: ").append(is_real_time_broadcast_enabled).append("\n");
    sb.append("  is_scroll_broadcast_enabled: ").append(is_scroll_broadcast_enabled).append("\n");
    sb.append("  is_zoom_broadcast_enabled: ").append(is_zoom_broadcast_enabled).append("\n");
    sb.append("  annotation_logo: ").append(annotation_logo).append("\n");
    sb.append("  pointer_tool_cursor: ").append(pointer_tool_cursor).append("\n");
    sb.append("  annotation_header_options: ").append(annotation_header_options).append("\n");
    sb.append("  is_annotation_navigation_widget_enabled: ").append(is_annotation_navigation_widget_enabled).append("\n");
    sb.append("  is_annotation_zoom_widget_enabled: ").append(is_annotation_zoom_widget_enabled).append("\n");
    sb.append("  is_annotation_download_widget_enabled: ").append(is_annotation_download_widget_enabled).append("\n");
    sb.append("  is_annotation_print_widget_enabled: ").append(is_annotation_print_widget_enabled).append("\n");
    sb.append("  is_annotation_help_widget_enabled: ").append(is_annotation_help_widget_enabled).append("\n");
    sb.append("  is_right_panel_enabled: ").append(is_right_panel_enabled).append("\n");
    sb.append("  is_thumbnails_panel_enabled: ").append(is_thumbnails_panel_enabled).append("\n");
    sb.append("  is_standard_header_always_shown: ").append(is_standard_header_always_shown).append("\n");
    sb.append("  is_toolbar_enabled: ").append(is_toolbar_enabled).append("\n");
    sb.append("  is_text_annotation_button_enabled: ").append(is_text_annotation_button_enabled).append("\n");
    sb.append("  is_rectangle_annotation_button_enabled: ").append(is_rectangle_annotation_button_enabled).append("\n");
    sb.append("  is_point_annotation_button_enabled: ").append(is_point_annotation_button_enabled).append("\n");
    sb.append("  is_strikeout_annotation_button_enabled: ").append(is_strikeout_annotation_button_enabled).append("\n");
    sb.append("  is_polyline_annotation_button_enabled: ").append(is_polyline_annotation_button_enabled).append("\n");
    sb.append("  is_typewriter_annotation_button_enabled: ").append(is_typewriter_annotation_button_enabled).append("\n");
    sb.append("  is_watermark_annotation_button_enabled: ").append(is_watermark_annotation_button_enabled).append("\n");
    sb.append("  viewer_logo: ").append(viewer_logo).append("\n");
    sb.append("  viewer_options: ").append(viewer_options).append("\n");
    sb.append("  is_viewer_navigation_widget_enabled: ").append(is_viewer_navigation_widget_enabled).append("\n");
    sb.append("  is_viewer_zoom_widget_enabled: ").append(is_viewer_zoom_widget_enabled).append("\n");
    sb.append("  is_viewer_download_widget_enabled: ").append(is_viewer_download_widget_enabled).append("\n");
    sb.append("  is_viewer_print_widget_enabled: ").append(is_viewer_print_widget_enabled).append("\n");
    sb.append("  is_viewer_help_widget_enabled: ").append(is_viewer_help_widget_enabled).append("\n");
    sb.append("  signedupOn: ").append(signedupOn).append("\n");
    sb.append("  signedinOn: ").append(signedinOn).append("\n");
    sb.append("  signin_count: ").append(signin_count).append("\n");
    sb.append("  roles: ").append(roles).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  guid: ").append(guid).append("\n");
    sb.append("  primary_email: ").append(primary_email).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

